#!/usr/bin/env bash
# Packs AdventureWorks.Domain and AdventureWorks.Application — plus their ProjectReference
# dependencies AdventureWorks.Common and AdventureWorks.Models, which `dotnet pack` turns into
# NuGet package dependencies pinned to this same version — into the local NuGet feed consumed
# by AdventureWorks.Functions.SalesOrderSaga. Run this before every restore/build of the
# Functions project after changing any of these four projects.
#
# The packed version is a fresh timestamp on every run — never a static string — so
# `dotnet restore` can never silently keep serving a stale cached package. The exact
# version just packed is written to eng/local-nuget-version.props, which the Functions
# project imports; if that file is missing, the Functions build fails loudly instead of
# falling back to an old package.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
FEED_DIR="${SCRIPT_DIR}/local-nuget-feed"
VERSION="1.0.0-local.$(date -u +%Y%m%d%H%M%S)"

mkdir -p "${FEED_DIR}"
rm -f "${FEED_DIR}"/*.nupkg

for project in AdventureWorks.Common AdventureWorks.Models AdventureWorks.Domain AdventureWorks.Application; do
  dotnet pack "${REPO_ROOT}/apps/api-dotnet/src/${project}/${project}.csproj" \
    -c Release -o "${FEED_DIR}" -p:Version="${VERSION}"
done

mkdir -p "${SCRIPT_DIR}/eng"
cat > "${SCRIPT_DIR}/eng/local-nuget-version.props" <<EOF
<Project>
  <!-- Generated by pack-local-nuget.sh. Do not edit by hand. -->
  <PropertyGroup>
    <AdventureWorksSharedPackageVersion>${VERSION}</AdventureWorksSharedPackageVersion>
  </PropertyGroup>
</Project>
EOF

echo "Packed AdventureWorks.Domain/AdventureWorks.Application @ ${VERSION} -> ${FEED_DIR}"
echo "If dotnet restore still resolves an old version, run: dotnet nuget locals all --clear"
