namespace AdventureWorks.Models.Features.Sales;

/// <summary>
/// Top-level response model for the sales dashboard endpoint, containing overall KPIs,
/// top performer rankings, territory breakdown, and monthly sales trend data.
/// </summary>
public sealed class SalesDashboardModel
{
    /// <summary>Total revenue across all sales orders (sum of TotalDue).</summary>
    public decimal TotalRevenue { get; set; }

    /// <summary>Total number of sales orders in the dataset.</summary>
    public int OrderCount { get; set; }

    /// <summary>Average revenue per sales order (TotalRevenue / OrderCount).</summary>
    public decimal AverageOrderValue { get; set; }

    /// <summary>Top 5 sales persons ranked by total revenue, descending.</summary>
    public List<DashboardTopPerformerModel> TopPerformers { get; set; } = [];

    /// <summary>Revenue and order count aggregated by sales territory, ordered by revenue descending.</summary>
    public List<DashboardTerritoryModel> TerritoryBreakdown { get; set; } = [];

    /// <summary>Monthly revenue and order count for the trailing 24 months, ordered chronologically.</summary>
    public List<DashboardMonthlySalesTrendModel> MonthlySalesTrend { get; set; } = [];
}

/// <summary>
/// Aggregate metrics for a single sales person, used in the top-performers ranking.
/// </summary>
public sealed class DashboardTopPerformerModel
{
    /// <summary>Primary key of the sales person (BusinessEntityId).</summary>
    public int SalesPersonId { get; set; }

    /// <summary>Full name of the sales person (FirstName + LastName).</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>Total revenue generated by this sales person (sum of TotalDue).</summary>
    public decimal Revenue { get; set; }

    /// <summary>Number of sales orders attributed to this sales person.</summary>
    public int OrderCount { get; set; }
}

/// <summary>
/// Aggregate metrics for a single sales territory, used in the territory breakdown.
/// </summary>
public sealed class DashboardTerritoryModel
{
    /// <summary>Primary key of the sales territory.</summary>
    public int TerritoryId { get; set; }

    /// <summary>Display name of the sales territory.</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>ISO country/region code associated with the territory.</summary>
    public string CountryCode { get; set; } = string.Empty;

    /// <summary>Number of sales orders placed within this territory.</summary>
    public int OrderCount { get; set; }

    /// <summary>Total revenue generated within this territory (sum of TotalDue).</summary>
    public decimal Revenue { get; set; }
}

/// <summary>
/// Revenue and order count for a single calendar month, used in the monthly sales trend.
/// </summary>
public sealed class DashboardMonthlySalesTrendModel
{
    /// <summary>Calendar year of the data point (e.g. 2014).</summary>
    public int Year { get; set; }

    /// <summary>Calendar month of the data point (1–12).</summary>
    public int Month { get; set; }

    /// <summary>Number of sales orders placed in this month.</summary>
    public int OrderCount { get; set; }

    /// <summary>Total revenue for this month (sum of TotalDue).</summary>
    public decimal Revenue { get; set; }
}
