-- <Migration ID="f94e2a12-0eb5-4e99-adee-54d70229f384" />
GO
/****************************************************************************************************************
** CREATED BY:   Mick Letofsky
** CREATED DATE: 2019.05.08
** CREATED FOR:  PBI 437
** CREATED:      Baseline code for AdventureWorks SQL Change Automation Project.
****************************************************************************************************************/

IF DATABASE_PRINCIPAL_ID(N'amy0') IS NULL
CREATE USER [amy0] WITHOUT LOGIN

IF DATABASE_PRINCIPAL_ID(N'brian3') IS NULL
CREATE USER [brian3] WITHOUT LOGIN

IF DATABASE_PRINCIPAL_ID(N'david8') IS NULL
CREATE USER [david8] WITHOUT LOGIN

IF DATABASE_PRINCIPAL_ID(N'garrett1') IS NULL
CREATE USER [garrett1] WITHOUT LOGIN

IF DATABASE_PRINCIPAL_ID(N'jae0') IS NULL
CREATE USER [jae0] WITHOUT LOGIN

IF DATABASE_PRINCIPAL_ID(N'jillian0') IS NULL
CREATE USER [jillian0] WITHOUT LOGIN

IF DATABASE_PRINCIPAL_ID(N'josé1') IS NULL
CREATE USER [josé1] WITHOUT LOGIN

IF DATABASE_PRINCIPAL_ID(N'linda3') IS NULL
CREATE USER [linda3] WITHOUT LOGIN

IF DATABASE_PRINCIPAL_ID(N'lynn0') IS NULL
CREATE USER [lynn0] WITHOUT LOGIN

IF DATABASE_PRINCIPAL_ID(N'michael9') IS NULL
CREATE USER [michael9] WITHOUT LOGIN

IF DATABASE_PRINCIPAL_ID(N'pamela0') IS NULL
CREATE USER [pamela0] WITHOUT LOGIN

IF DATABASE_PRINCIPAL_ID(N'rachel0') IS NULL
CREATE USER [rachel0] WITHOUT LOGIN

IF DATABASE_PRINCIPAL_ID(N'ranjit0') IS NULL
CREATE USER [ranjit0] WITHOUT LOGIN

IF DATABASE_PRINCIPAL_ID(N'shu0') IS NULL
CREATE USER [shu0] WITHOUT LOGIN

IF DATABASE_PRINCIPAL_ID(N'stephen0') IS NULL
CREATE USER [stephen0] WITHOUT LOGIN

IF DATABASE_PRINCIPAL_ID(N'syed0') IS NULL
CREATE USER [syed0] WITHOUT LOGIN

IF DATABASE_PRINCIPAL_ID(N'tete0') IS NULL
CREATE USER [tete0] WITHOUT LOGIN

IF DATABASE_PRINCIPAL_ID(N'tsvi0') IS NULL
CREATE USER [tsvi0] WITHOUT LOGIN

IF DATABASE_PRINCIPAL_ID(N'SalesManagers') IS NULL
BEGIN
	CREATE ROLE [SalesManagers] AUTHORIZATION [dbo]
END

IF DATABASE_PRINCIPAL_ID(N'SalesPersons') IS NULL
BEGIN
	CREATE ROLE [SalesPersons] AUTHORIZATION [dbo]
END

ALTER ROLE [SalesManagers] ADD MEMBER [amy0]
ALTER ROLE [SalesManagers] ADD MEMBER [brian3]
ALTER ROLE [SalesManagers] ADD MEMBER [stephen0]
ALTER ROLE [SalesManagers] ADD MEMBER [syed0]

ALTER ROLE [SalesPersons] ADD MEMBER [david8]
ALTER ROLE [SalesPersons] ADD MEMBER [garrett1]
ALTER ROLE [SalesPersons] ADD MEMBER [jae0]
ALTER ROLE [SalesPersons] ADD MEMBER [jillian0]
ALTER ROLE [SalesPersons] ADD MEMBER [josé1]
ALTER ROLE [SalesPersons] ADD MEMBER [linda3]
ALTER ROLE [SalesPersons] ADD MEMBER [lynn0]
ALTER ROLE [SalesPersons] ADD MEMBER [michael9]
ALTER ROLE [SalesPersons] ADD MEMBER [pamela0]
ALTER ROLE [SalesPersons] ADD MEMBER [rachel0]
ALTER ROLE [SalesPersons] ADD MEMBER [ranjit0]
ALTER ROLE [SalesPersons] ADD MEMBER [shu0]
ALTER ROLE [SalesPersons] ADD MEMBER [tete0]
ALTER ROLE [SalesPersons] ADD MEMBER [tsvi0]
